version: '3'
services:

  db:
    container_name: mysql_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: edo515
      MYSQL_DATABASE: todos
    ports:
      - "3306:3306" 
    volumes:
      - ./mysql_data:/var/lib/mysql


  app:
    container_name: vash_domophone
    build:
      context: D:/do/back
    ports:
      - "8000:8000"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - .env:/back/.env
    environment:
      APP_PORT: 8000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: edo515
      DB_NAME: todos

    restart: on-failure
    command: >
      sh -c "sleep 40 && npm run dev"
    depends_on:
      - db
    

